# LAB | Imbalanced

**Load the data**

In this challenge, we will be working with Credit Card Fraud dataset.

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv

Metadata

- **distance_from_home:** the distance from home where the transaction happened.
- **distance_from_last_transaction:** the distance from last transaction happened.
- **ratio_to_median_purchase_price:** Ratio of purchased price transaction to median purchase price.
- **repeat_retailer:** Is the transaction happened from same retailer.
- **used_chip:** Is the transaction through chip (credit card).
- **used_pin_number:** Is the transaction happened by using PIN number.
- **online_order:** Is the transaction an online order.
- **fraud:** Is the transaction fraudulent. **0=legit** -  **1=fraud**

In [1]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
fraud = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv")
fraud.head()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0

**Steps:**

- **1.** What is the distribution of our target variable? Can we say we're dealing with an imbalanced dataset?
- **2.** Train a LogisticRegression.
- **3.** Evaluate your model. Take in consideration class importance, and evaluate it by selection the correct metric.
- **4.** Run **Oversample** in order to balance our target variable and repeat the steps above, now with balanced data. Does it improve the performance of our model? 
- **5.** Now, run **Undersample** in order to balance our target variable and repeat the steps above (1-3), now with balanced data. Does it improve the performance of our model?
- **6.** Finally, run **SMOTE** in order to balance our target variable and repeat the steps above (1-3), now with balanced data. Does it improve the performance of our model?

---
# Solved LAB | Imbalanced
---

## **Load & View the data**

In this challenge, we will be working with Credit Card Fraud dataset.

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv

Metadata

- **distance_from_home:** the distance from home where the transaction happened.
- **distance_from_last_transaction:** the distance from last transaction happened.
- **ratio_to_median_purchase_price:** Ratio of purchased price transaction to median purchase price.
- **repeat_retailer:** Is the transaction happened from same retailer.
- **used_chip:** Is the transaction through chip (credit card).
- **used_pin_number:** Is the transaction happened by using PIN number.
- **online_order:** Is the transaction an online order.
- **fraud:** Is the transaction fraudulent. **0=legit** -  **1=fraud**

| Feature Name                     | Description                                                   | Data Type | Variable Type            | Action  | Role    |
|----------------------------------|---------------------------------------------------------------|-----------|--------------------------|---------|---------|
| `distance_from_home`               | Distance from home where the transaction occurred            | float64   | Numerical (Continuous)   | Scale   | Feature |
| `distance_from_last_transaction`   | Distance from previous transaction                           | float64   | Numerical (Continuous)   | Scale   | Feature |
| `ratio_to_median_purchase_price`   | Ratio of transaction amount to median purchase price         | float64   | Numerical (Continuous)   | Scale   | Feature |
| `repeat_retailer`                  | Transaction from same retailer (0 = No, 1 = Yes)             | float64   | Categorical (Binary)     | None    | Feature |
| `used_chip`                        | Transaction used chip (0 = No, 1 = Yes)                      | float64   | Categorical (Binary)     | None    | Feature |
| `used_pin_number`                  | Transaction used PIN (0 = No, 1 = Yes)                       | float64   | Categorical (Binary)     | None    | Feature |
| `online_order`                     | Transaction is online (0 = No, 1 = Yes)                      | float64   | Categorical (Binary)     | None    | Feature |
| `fraud`                            | Fraud label (0 = Legit, 1 = Fraud)                           | float64   | Categorical (Binary)     | None    | Target  |

In [3]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
fraud = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv")
fraud.head()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0

In [5]:
fraud.info()
#no nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   distance_from_home              1000000 non-null  float64
 1   distance_from_last_transaction  1000000 non-null  float64
 2   ratio_to_median_purchase_price  1000000 non-null  float64
 3   repeat_retailer                 1000000 non-null  float64
 4   used_chip                       1000000 non-null  float64
 5   used_pin_number                 1000000 non-null  float64
 6   online_order                    1000000 non-null  float64
 7   fraud                           1000000 non-null  float64
dtypes: float64(8)
memory usage: 61.0 MB

In [6]:
# unique values in each column
for col in fraud.columns:
    print(f"Unique values in '{col}': {fraud[col].nunique()}")
# no categorical columns, all are numerical

Unique values in 'distance_from_home': 1000000
Unique values in 'distance_from_last_transaction': 1000000
Unique values in 'ratio_to_median_purchase_price': 1000000
Unique values in 'repeat_retailer': 2
Unique values in 'used_chip': 2
Unique values in 'used_pin_number': 2
Unique values in 'online_order': 2
Unique values in 'fraud': 2

In [7]:
# unique values in each column
for col in fraud.columns:
    print(f"Unique values in '{col}': {fraud[col].unique()}")
# no categorical columns, all are numerical

Unique values in 'distance_from_home': [57.87785658 10.8299427   5.09107949 ...  2.91485699  4.25872939
 58.10812496]
Unique values in 'distance_from_last_transaction': [0.31114001 0.1755915  0.80515259 ... 1.47268669 0.24202337 0.31811012]
Unique values in 'ratio_to_median_purchase_price': [1.94593998 1.29421881 0.42771456 ... 0.21807549 0.47582206 0.38691985]
Unique values in 'repeat_retailer': [1. 0.]
Unique values in 'used_chip': [1. 0.]
Unique values in 'used_pin_number': [0. 1.]
Unique values in 'online_order': [0. 1.]
Unique values in 'fraud': [0. 1.]

In [8]:
fraud.duplicated().sum()
#no duplicates

np.int64(0)

---
## **Data Cleaning**
---

#### **Check the shape of your data**

In [9]:
# Check the shape of the dataset*
print("Dataset Shape:", fraud.shape)
# number of rows 
print("Number of rows:", fraud.shape[0])
# number of columns
print("Number of columns:", fraud.shape[1])

Dataset Shape: (1000000, 8)
Number of rows: 1000000
Number of columns: 8

#### **Check for data types**

In [10]:
print("Data Types:")
display(fraud.dtypes)
# data type correctly assigned to each column

Data Types:

distance_from_home                float64
distance_from_last_transaction    float64
ratio_to_median_purchase_price    float64
repeat_retailer                   float64
used_chip                         float64
used_pin_number                   float64
online_order                      float64
fraud                             float64
dtype: object

#### **Check for missing values**

In [11]:
print("Missing Values:")
display(fraud.isnull().sum())
# no missing values in any column

Missing Values:

distance_from_home                0
distance_from_last_transaction    0
ratio_to_median_purchase_price    0
repeat_retailer                   0
used_chip                         0
used_pin_number                   0
online_order                      0
fraud                             0
dtype: int64

---
## **Perform Train Test Split**
- split fraud dataset into train and test sets (stratify by target variable to maintain class distribution)

**Define target (y)**

In [12]:
# define target variable
y = fraud["fraud"]

**Define features (X)**

In [13]:
# define features: 
X = fraud.drop(["fraud"], axis=1)
print(f"Shape of data after dropping 'fraud': {X.shape}")
display(X.head())

Shape of data after dropping 'fraud': (1000000, 7)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0

**SPLIT**

In [14]:
# define train-test split sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

#display the shapes of the resulting sets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (800000, 7)
X_test shape: (200000, 7)
y_train shape: (800000,)
y_test shape: (200000,)

---
## **Feature Engineering**

1. Identity Categorical vs Numerical Features

In [15]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Boolean columns (already 0/1)
bool_cols = ['repeat_retailer', 'used_chip', 'used_pin_number', 'online_order']

# Categorical columns (more than 2 categories)
cat_cols = [] # no categorical columns, all are numerical other than the target variable

# Numerical columns
num_cols = ['distance_from_home', 'distance_from_last_transaction', 'ratio_to_median_purchase_price']

2. one hot encode categorical features (not boolean)

In [16]:
ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

X_train_cat = pd.DataFrame(
    ohe.fit_transform(X_train[cat_cols]),
    columns=ohe.get_feature_names_out(cat_cols),
    index=X_train.index
)

X_test_cat = pd.DataFrame(
    ohe.transform(X_test[cat_cols]),
    columns=ohe.get_feature_names_out(cat_cols),
    index=X_test.index
)

3. Scale Numerical Columns

In [17]:
scaler = StandardScaler()

X_train_num = pd.DataFrame(
    scaler.fit_transform(X_train[num_cols]),
    columns=num_cols,
    index=X_train.index
)

X_test_num = pd.DataFrame(
    scaler.transform(X_test[num_cols]),
    columns=num_cols,
    index=X_test.index
)

4. Convert Booleans to int (True=1 , False=0)

In [18]:
# Boolean columns (already 0/1)
X_train_bool = X_train[bool_cols]
X_test_bool = X_test[bool_cols]

5. Combine & Save Train Test sets CSVs

In [19]:
# Combine all features
X_train = pd.concat([X_train_num, X_train_bool, X_train_cat], axis=1)
X_test = pd.concat([X_test_num, X_test_bool, X_test_cat], axis=1)

# display the shapes of the resulting sets
print("X_train shape after encoding and scaling:", X_train.shape)
display(X_train.head())
print("X_test shape after encoding and scaling:", X_test.shape)
display(X_test.head())

print("y_train shape:", y_train.shape)
display(y_train.head())
print("y_test shape:", y_test.shape)
display(y_test.head())

# ---- Save preprocessed data to CSV files ----
X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

X_train shape after encoding and scaling: (800000, 7)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order
950236,-0.353541,0.083049,-0.573726,1.0,1.0,0.0,1.0
358251,-0.175683,-0.156580,0.315170,1.0,1.0,0.0,1.0
597434,0.078467,-0.070319,-0.539590,1.0,0.0,0.0,1.0
296537,-0.250188,-0.187940,-0.526985,1.0,0.0,0.0,0.0
235768,0.839938,-0.010984,-0.192063,1.0,0.0,0.0,0.0

X_test shape after encoding and scaling: (200000, 7)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order
677554,-0.319315,-0.180502,-0.224534,1.0,0.0,0.0,1.0
145563,2.609480,-0.182467,-0.243314,1.0,0.0,0.0,1.0
481407,0.066344,-0.120437,-0.558983,1.0,1.0,0.0,1.0
619391,-0.003421,21.803298,-0.453151,1.0,1.0,0.0,0.0
147719,-0.390139,-0.172616,0.190981,0.0,0.0,0.0,0.0

y_train shape: (800000,)

950236    0.0
358251    0.0
597434    0.0
296537    0.0
235768    0.0
Name: fraud, dtype: float64

y_test shape: (200000,)

677554    0.0
145563    1.0
481407    0.0
619391    0.0
147719    0.0
Name: fraud, dtype: float64

---
## ** **

---
## **Steps:**

#### **Step 1.** What is the distribution of our target variable? Can we say we're dealing with an imbalanced dataset?

In [21]:
print("Train class distribution:")
print(pd.Series(y_train).value_counts())
print(pd.Series(y_train).value_counts(normalize=True))
print(100*'-')
print("\nTest class distribution:")
print(pd.Series(y_test).value_counts())
print(pd.Series(y_test).value_counts(normalize=True))

Train class distribution:
fraud
0.0    730078
1.0     69922
Name: count, dtype: int64
fraud
0.0    0.912597
1.0    0.087402
Name: proportion, dtype: float64
----------------------------------------------------------------------------------------------------

Test class distribution:
fraud
0.0    182519
1.0     17481
Name: count, dtype: int64
fraud
0.0    0.912595
1.0    0.087405
Name: proportion, dtype: float64

---
#### **Step 2.** Train a LogisticRegression.

---
#### **Step 3.** Evaluate your model. Take in consideration class importance, and evaluate it by selection the correct metric.

---
#### **Step 4.** Run **Oversample** in order to balance our target variable and repeat the steps above, now with balanced data. Does it improve the performance of our model?

---
#### **Step 5.** Now, run **Undersample** in order to balance our target variable and repeat the steps above (1-3), now with balanced data. Does it improve the performance of our model?

---
### **Step 6.** Finally, run **SMOTE** in order to balance our target variable and repeat the steps above (1-3), now with balanced data. Does it improve the performance of our model?